<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="beatles.xsl" type="text/xsl"?>

<!DOCTYPE beatles [
<!ELEMENT beatles (discos)*>
<!ELEMENT discos (canciones)*>
<!ELEMENT canciones (cancion*)>
<!ELEMENT cancion (#PCDATA)>
<!ATTLIST discos
titulo CDATA #REQUIRED
discografica CDATA #IMPLIED
agno CDATA #IMPLIED>
<!ATTLIST cancion
id ID #IMPLIED
titulo CDATA #REQUIRED
agno CDATA #IMPLIED
autor (Lennon | Mcartney | Harrison | Star) "Lennon">
]>
<beatles>
  <discos titulo="LET IT BE" discografica="EMI" agno="1970">
    <canciones>
      <cancion id= "a1" titulo="Two of us" agno="1970"
	       autor="Lennon"/>
      <cancion id= "a2" titulo="Dig a pony" agno="1970"
	       autor="Mcartney"/>
      <cancion id= "a3" titulo="Across the Universe" agno="1970"
	       autor="Lennon"/>
      <cancion id= "a4" titulo="I Me Mine" agno="1970"
	       autor="Harrison"/>
      <cancion id= "a5" titulo="Dig It" agno="1970"
	       autor="Lennon"/>
      <cancion id= "a6" titulo="Let it Be" agno="1970"
	       autor="Lennon"/>
      <cancion id= "a7" titulo="Maggie Mae" agno="1970"
	       autor="Lennon"/>
      <cancion id= "a8" titulo="I've got a feeling" agno="1970"
	       autor="Mcartney"/>
      <cancion id= "a9" titulo="The long and widing road"
	       agno="1970" autor="Lennon"/>
    </canciones>
  </discos>
  <discos titulo="MAGICAL MISTERY TOUR" discografica="EMI"
	  agno="1967">
    <canciones>
      <cancion id= "b1" titulo="Magical Mistery Tour" agno="1967"
	       autor="Lennon"/>
      <cancion id= "b2" titulo="The fool on the hill" agno="1967"
	       autor="Mcartney"/>
      <cancion id= "b3" titulo="Flying" agno="1967"
	       autor="Lennon"/>
      <cancion id= "b4" titulo="Blue Jay Way" agno="1967"
	       autor="Harrison"/>
      <cancion id= "b5" titulo="Your Mother should know"
	       agno="1967" autor="Lennon"/>
      <cancion id= "b6" titulo="I am the walrus" agno="1967"
	       autor="Lennon"/>
      <cancion id= "b7" titulo="Hellow Goodbye" agno="1967"
	       autor="Lennon"/>
      <cancion id= "b8" titulo="Strawberry Fields Forever"
	       agno="1967" autor="Mcartney"/>
      <cancion id= "b9" titulo="Penny Lane" agno="1967"
	       autor="Lennon"/>
      <cancion id= "b10" titulo="Baby you're a rich man"
	       agno="1967" autor="Mcartney"/>
      <cancion id= "b11" titulo="All you need is love"
	       agno="1967" autor="Mcartney"/>
    </canciones>
  </discos>
</beatles>
